### ISSUE TITLE
xsltproc is required for the catkin build

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#86]
```
Errors     << vrep_ros_interface:make /home/andrew/scott-eu/simulation-ros/logs/vrep_ros_interface/build.make.000.log                        
Traceback (most recent call last):
  File "/home/andrew/scott-eu/simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 96, in <module>
    runprogram('xsltproc', '-o', output('reference.html'), rel('xsl/reference.xsl'), input_xml)
  File "/home/andrew/scott-eu/simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 50, in runprogram
    runsubprocess(what, [what] + list(args))
  File "/home/andrew/scott-eu/simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 38, in runsubprocess
    child = subprocess.Popen(args)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make[2]: *** [generated/stubs.cpp] Error 1
make[1]: *** [CMakeFiles/v_repExtRosInterface.dir/all] Error 2
make: *** [all] Error 2
cd /home/andrew/scott-eu/simulation-ros/build/vrep_ros_interface; catkin build --get-env vrep_ros_interface | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

Solution: `sudo apt-get install xsltproc`

**Comment by albertohata** [comment]
I included this instruction in the readme.
