### ISSUE TITLE
"Premature end of file" exception

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#91]
```
sandbox-twin-shelf_1       | [pool-5-thread-1] DEBUG org.eclipse.lyo.trs.consumer.util.TrsBasicAuthOslcClient - Getting jena model for server response for resource: http://localhost:8080/sandbox-whc/services/trs
sandbox-twin-shelf_1       | [pool-5-thread-1] ERROR org.apache.jena.riot - Premature end of file.
sandbox-twin-shelf_1       | [pool-5-thread-1] ERROR org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler - Error polling & processing TRS change logs
sandbox-twin-shelf_1       | org.apache.jena.riot.RiotException: Premature end of file.
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:147)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$ErrorHandlerBridge.fatalError(ReaderRIOTRDFXML.java:260)
sandbox-twin-shelf_1       | 	at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:47)
sandbox-twin-shelf_1       | 	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:199)
sandbox-twin-shelf_1       | 	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.fatalError(XMLHandler.java:229)
sandbox-twin-shelf_1       | 	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.impl.XMLDocumentScannerImpl$XMLDeclDispatcher.dispatch(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
sandbox-twin-shelf_1       | 	at org.apache.jena.rdfxml.xmlinput.impl.RDFXMLParser.parse(RDFXMLParser.java:150)
sandbox-twin-shelf_1       | 	at org.apache.jena.rdfxml.xmlinput.ARP.load(ARP.java:118)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.lang.ReaderRIOTRDFXML.parse(ReaderRIOTRDFXML.java:135)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.lang.ReaderRIOTRDFXML.read(ReaderRIOTRDFXML.java:79)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFParser.read(RDFParser.java:334)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:324)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:273)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:498)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFDataMgr.parseFromInputStream(RDFDataMgr.java:870)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:268)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:254)
sandbox-twin-shelf_1       | 	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
sandbox-twin-shelf_1       | 	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:275)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.util.TrsBasicAuthOslcClient.extractModelFromResponse(TrsBasicAuthOslcClient.java:151)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.util.TrsBasicAuthOslcClient.fetchResourceUsingBaseAuth(TrsBasicAuthOslcClient.java:81)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TRSTaskHandler.fetchTRSRemoteResource(TRSTaskHandler.java:79)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler.extractRemoteTrs(TrsProviderHandler.java:689)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler.pollAndProcessChanges(TrsProviderHandler.java:259)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler.processTRSTask(TrsProviderHandler.java:132)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TRSTaskHandler.run(TRSTaskHandler.java:114)
```

**Comment by berezovskyi** [comment]
This happens when the server renders an HTML page instead of a proper RDF response:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/64734/41593020-ebde79ea-73be-11e8-9ae3-cd5c8cb6e9ee.png">

**Comment by berezovskyi** [comment]
wontfix unless @jadelkhoury or @jamsden insist on moving this to Lyo
