### ISSUE TITLE
Unexpected TRS server rollbacks 

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#93]
```
sandbox-twin-shelf_1       | org.eclipse.lyo.trs.consumer.exceptions.ServerRollBackException: The sync event can not be found. The sever provinding the trs at: http://sandbox-whc:8080/services/trs seems to have been rollecd back to a previous state
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler.fetchUpdatedChangeLogs(TrsProviderHandler.java:191)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler.pollAndProcessChanges(TrsProviderHandler.java:331)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TrsProviderHandler.processTRSTask(TrsProviderHandler.java:133)
sandbox-twin-shelf_1       | 	at org.eclipse.lyo.trs.consumer.handlers.TRSTaskHandler.run(TRSTaskHandler.java:117)
```

**Comment by berezovskyi** [comment]
wontfix unless @jadelkhoury or @jamsden insist on moving this to Lyo
